const Overwatch = [{
    "rank": null,
    "percentile": null,
    "displayName": "Time Played",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 252330,
    "displayValue": "2d 22h 05m",
    "displayType": "TimeSeconds"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Wins",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 300,
    "displayValue": "300",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Matches Played",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 0,
    "displayValue": "0",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Time Spent on Fire",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 20295,
    "displayValue": "5h 38m 15s",
    "displayType": "TimeSeconds"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Cards",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 232,
    "displayValue": "232",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Win %",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 300.0,
    "displayValue": "300.0%",
    "displayType": "NumberPercentage"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Medals",
    "displayCategory": "Medals",
    "category": "medals",
    "metadata": {},
    "value": 1556,
    "displayValue": "1,556",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Gold Medals",
    "displayCategory": "Medals",
    "category": "medals",
    "metadata": {},
    "value": 609,
    "displayValue": "609",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Silver Medals",
    "displayCategory": "Medals",
    "category": "medals",
    "metadata": {},
    "value": 494,
    "displayValue": "494",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Bronze Medals",
    "displayCategory": "Medals",
    "category": "medals",
    "metadata": {},
    "value": 452,
    "displayValue": "452",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Multikills",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 53,
    "displayValue": "53",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Solo Kills",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 424,
    "displayValue": "424",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Objective Kills",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 2974,
    "displayValue": "2,974",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Environmental Kills",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 43,
    "displayValue": "43",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Final Blows",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 2514,
    "displayValue": "2,514",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Damage Done",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 1896034,
    "displayValue": "1,896,034",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Healing Done",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 1463231,
    "displayValue": "1,463,231",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Eliminations",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 6578,
    "displayValue": "6,578",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Deaths",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 2969,
    "displayValue": "2,969",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "K/D",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 2.2155607948804312,
    "displayValue": "2.22",
    "displayType": "NumberPrecision2"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Kills/Game",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 6578.0,
    "displayValue": "6,578.00",
    "displayType": "NumberPrecision2"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Objective Time",
    "displayCategory": "Objective",
    "category": "objective",
    "metadata": {},
    "value": 29860,
    "displayValue": "8h 17m 40s",
    "displayType": "TimeSeconds"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Defensive Assists",
    "displayCategory": "Objective",
    "category": "objective",
    "metadata": {},
    "value": 2847,
    "displayValue": "2,847",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Offensive Assists",
    "displayCategory": "Objective",
    "category": "objective",
    "metadata": {},
    "value": 1964,
    "displayValue": "1,964",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Most Eliminations",
    "displayCategory": "Bests",
    "category": "bests",
    "metadata": {},
    "value": 36,
    "displayValue": "36",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Most Final Blows",
    "displayCategory": "Bests",
    "category": "bests",
    "metadata": {},
    "value": 25,
    "displayValue": "25",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Most Damage Done",
    "displayCategory": "Bests",
    "category": "bests",
    "metadata": {},
    "value": 17155,
    "displayValue": "17,155",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Most Healing Done",
    "displayCategory": "Bests",
    "category": "bests",
    "metadata": {},
    "value": 13843,
    "displayValue": "13,843",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Most Defensive Assists",
    "displayCategory": "Bests",
    "category": "bests",
    "metadata": {},
    "value": 33,
    "displayValue": "33",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Most Offensive Assists",
    "displayCategory": "Bests",
    "category": "bests",
    "metadata": {},
    "value": 24,
    "displayValue": "24",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Most Objective Kills",
    "displayCategory": "Bests",
    "category": "bests",
    "metadata": {},
    "value": 26,
    "displayValue": "26",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Most Objective Time",
    "displayCategory": "Bests",
    "category": "bests",
    "metadata": {},
    "value": 318,
    "displayValue": "05m 18s",
    "displayType": "TimeSeconds"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Most Solo Kills",
    "displayCategory": "Bests",
    "category": "bests",
    "metadata": {},
    "value": 25,
    "displayValue": "25",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Most Time Spent on Fire",
    "displayCategory": "Bests",
    "category": "bests",
    "metadata": {},
    "value": 475,
    "displayValue": "07m 55s",
    "displayType": "TimeSeconds"
  }
];

const Division2 = [{
    "rank": null,
    "percentile": 59.0,
    "displayName": "Time Played",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 486309,
    "displayValue": "5d 15h 05m",
    "displayType": "TimeSeconds"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "PvP Kills",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 25292,
    "displayValue": "25,292",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "NPC Kills",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 674722,
    "displayValue": "674,722",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Skill Kills",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 562764,
    "displayValue": "562,764",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.5,
    "displayName": "Headshots",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 492569,
    "displayValue": "492,569",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 96.7,
    "displayName": "Items Looted",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 26795,
    "displayValue": "26,795",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Total XP",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 2147812849,
    "displayValue": "2,147,812,849",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Clan XP",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 0,
    "displayValue": "0",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Specialization",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": "Demolitionist",
    "displayValue": "Demolitionist",
    "displayType": "String"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Sharpshooter Kills",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 117457,
    "displayValue": "117,457",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Survivalist Kills",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 149978,
    "displayValue": "149,978",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Demolitionist Kills",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 722682,
    "displayValue": "722,682",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 98.8,
    "displayName": "E-Credit Balance",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 3415207,
    "displayValue": "3,415,207",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 97.1,
    "displayName": "Commendations",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 314,
    "displayValue": "314",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 97.3,
    "displayName": "Curr Comm. Score",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 4140,
    "displayValue": "4,140",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 74.0,
    "displayName": "Gear Score",
    "displayCategory": "PvE",
    "category": "pve",
    "metadata": {},
    "value": 500,
    "displayValue": "500",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 36.0,
    "displayName": "Player Level",
    "displayCategory": "PvE",
    "category": "pve",
    "metadata": {},
    "value": 30,
    "displayValue": "30",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "PvE XP",
    "displayCategory": "PvE",
    "category": "pve",
    "metadata": {},
    "value": 2147349027,
    "displayValue": "2,147,349,027",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 98.7,
    "displayName": "Time Played",
    "displayCategory": "PvE",
    "category": "pve",
    "metadata": {},
    "value": 4760613,
    "displayValue": "55d 02h 23m",
    "displayType": "TimeSeconds"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Elite Kills",
    "displayCategory": "PvE",
    "category": "pve",
    "metadata": {},
    "value": 0,
    "displayValue": "0",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 89.0,
    "displayName": "Named Kills",
    "displayCategory": "PvE",
    "category": "pve",
    "metadata": {},
    "value": 1439,
    "displayValue": "1,439",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Hyena Kills",
    "displayCategory": "PvE",
    "category": "pve",
    "metadata": {},
    "value": 214564,
    "displayValue": "214,564",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 88.0,
    "displayName": "OutCasts Kills",
    "displayCategory": "PvE",
    "category": "pve",
    "metadata": {},
    "value": 7159,
    "displayValue": "7,159",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "TrueSons Kills",
    "displayCategory": "PvE",
    "category": "pve",
    "metadata": {},
    "value": 434215,
    "displayValue": "434,215",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 95.0,
    "displayName": "BlackTusk Kills",
    "displayCategory": "PvE",
    "category": "pve",
    "metadata": {},
    "value": 24271,
    "displayValue": "24,271",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 23.0,
    "displayName": "DZ Level",
    "displayCategory": "Dark Zone",
    "category": "darkZone",
    "metadata": {},
    "value": 6,
    "displayValue": "6",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 84.0,
    "displayName": "DZ XP",
    "displayCategory": "Dark Zone",
    "category": "darkZone",
    "metadata": {},
    "value": 413657,
    "displayValue": "413,657",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 42.0,
    "displayName": "Time Played",
    "displayCategory": "Dark Zone",
    "category": "darkZone",
    "metadata": {},
    "value": 6918,
    "displayValue": "1h 55m 18s",
    "displayType": "TimeSeconds"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Rogues Killed",
    "displayCategory": "Dark Zone",
    "category": "darkZone",
    "metadata": {},
    "value": 0,
    "displayValue": "0",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 49.0,
    "displayName": "Rogue Time Played",
    "displayCategory": "Dark Zone",
    "category": "darkZone",
    "metadata": {},
    "value": 570,
    "displayValue": "09m 30s",
    "displayType": "TimeSeconds"
  },
  {
    "rank": null,
    "percentile": 44.0,
    "displayName": "Rogue Longest Time Played",
    "displayCategory": "Dark Zone",
    "category": "darkZone",
    "metadata": {},
    "value": 194,
    "displayValue": "03m 14s",
    "displayType": "TimeSeconds"
  },
  {
    "rank": null,
    "percentile": 42.0,
    "displayName": "Hyena Kills",
    "displayCategory": "Dark Zone",
    "category": "darkZone",
    "metadata": {},
    "value": 34,
    "displayValue": "34",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 45.0,
    "displayName": "OutCasts Kills",
    "displayCategory": "Dark Zone",
    "category": "darkZone",
    "metadata": {},
    "value": 29,
    "displayValue": "29",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 74.0,
    "displayName": "TrueSons Kills",
    "displayCategory": "Dark Zone",
    "category": "darkZone",
    "metadata": {},
    "value": 191,
    "displayValue": "191",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "BlackTusk Kills",
    "displayCategory": "Dark Zone",
    "category": "darkZone",
    "metadata": {},
    "value": 0,
    "displayValue": "0",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 51.0,
    "displayName": "Elite Kills",
    "displayCategory": "Dark Zone",
    "category": "darkZone",
    "metadata": {},
    "value": 62,
    "displayValue": "62",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Named Kills",
    "displayCategory": "Dark Zone",
    "category": "darkZone",
    "metadata": {},
    "value": 0,
    "displayValue": "0",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 89.0,
    "displayName": "Conflict Rank",
    "displayCategory": "Conflict PvP",
    "category": "conflictPvp",
    "metadata": {},
    "value": 13,
    "displayValue": "13",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 90.0,
    "displayName": "Conflict XP",
    "displayCategory": "Conflict PvP",
    "category": "conflictPvp",
    "metadata": {},
    "value": 50165,
    "displayValue": "50,165",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 88.0,
    "displayName": "Time Played",
    "displayCategory": "Conflict PvP",
    "category": "conflictPvp",
    "metadata": {},
    "value": 13739,
    "displayValue": "3h 48m 59s",
    "displayType": "TimeSeconds"
  },
  {
    "rank": null,
    "percentile": 98.6,
    "displayName": "Bleeding Kills",
    "displayCategory": "Kills",
    "category": "kills",
    "metadata": {},
    "value": 4694,
    "displayValue": "4,694",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Burning Kills",
    "displayCategory": "Kills",
    "category": "kills",
    "metadata": {},
    "value": 46748,
    "displayValue": "46,748",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 97.0,
    "displayName": "Shocked Kills",
    "displayCategory": "Kills",
    "category": "kills",
    "metadata": {},
    "value": 550,
    "displayValue": "550",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.2,
    "displayName": "Ensnare Kills",
    "displayCategory": "Kills",
    "category": "kills",
    "metadata": {},
    "value": 640,
    "displayValue": "640",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Headshot Kills",
    "displayCategory": "Kills",
    "category": "kills",
    "metadata": {},
    "value": 82596,
    "displayValue": "82,596",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 62.0,
    "displayName": "Shotgun Kills",
    "displayCategory": "Kills",
    "category": "kills",
    "metadata": {},
    "value": 144,
    "displayValue": "144",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "SMG Kills",
    "displayCategory": "Kills",
    "category": "kills",
    "metadata": {},
    "value": 81703,
    "displayValue": "81,703",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 97.3,
    "displayName": "Turret Kills",
    "displayCategory": "Kills",
    "category": "kills",
    "metadata": {},
    "value": 599,
    "displayValue": "599",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 82.0,
    "displayName": "Pistol Kills",
    "displayCategory": "Kills",
    "category": "kills",
    "metadata": {},
    "value": 224,
    "displayValue": "224",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 98.8,
    "displayName": "Rifle Kills",
    "displayCategory": "Kills",
    "category": "kills",
    "metadata": {},
    "value": 599,
    "displayValue": "599",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 95.5,
    "displayName": "Grenade Kills",
    "displayCategory": "Kills",
    "category": "kills",
    "metadata": {},
    "value": 503,
    "displayValue": "503",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.5,
    "displayName": "Items Looted/Min",
    "displayCategory": "",
    "category": null,
    "metadata": {},
    "value": 0.06,
    "displayValue": "0.06",
    "displayType": "NumberPrecision2"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "PvP Kills/Min",
    "displayCategory": "",
    "category": null,
    "metadata": {},
    "value": 0.05,
    "displayValue": "0.05",
    "displayType": "NumberPrecision2"
  },
  {
    "rank": null,
    "percentile": 99.8,
    "displayName": "NPC Kills/Min",
    "displayCategory": "",
    "category": null,
    "metadata": {},
    "value": 1.39,
    "displayValue": "1.39",
    "displayType": "NumberPrecision2"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Players Killed",
    "displayCategory": "",
    "category": null,
    "metadata": {},
    "value": 25419,
    "displayValue": "25,419",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.8,
    "displayName": "Skill Kills/Min",
    "displayCategory": "",
    "category": null,
    "metadata": {},
    "value": 1.16,
    "displayValue": "1.16",
    "displayType": "NumberPrecision2"
  }
];

const CounterStrike = [{
    "rank": null,
    "percentile": 99.0,
    "displayName": "Time Played",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 14102352,
    "displayValue": "163d 05h 19m",
    "displayType": "TimeSeconds"
  },
  {
    "rank": null,
    "percentile": 99.8,
    "displayName": "Score",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 2054698,
    "displayValue": "2,054,698",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.7,
    "displayName": "Kills",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 957526,
    "displayValue": "957,526",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 98.6,
    "displayName": "Deaths",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 205297,
    "displayValue": "205,297",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.2,
    "displayName": "K/D",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 4.664101277661144,
    "displayValue": "4.66",
    "displayType": "NumberPrecision2"
  },
  {
    "rank": null,
    "percentile": 99.8,
    "displayName": "Damage",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 145099944,
    "displayValue": "145,099,944",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Headshots",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 773115,
    "displayValue": "773,115",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 98.9,
    "displayName": "Dominations",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 3337,
    "displayValue": "3,337",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.7,
    "displayName": "Shots Fired",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 6322177,
    "displayValue": "6,322,177",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.8,
    "displayName": "Shots Hit",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 1804352,
    "displayValue": "1,804,352",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 98.4,
    "displayName": "Shots Accuracy",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 28.5400424568942,
    "displayValue": "28.5%",
    "displayType": "NumberPercentage"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Snipers Killed",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 24431,
    "displayValue": "24,431",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Domination Overkills",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 3908,
    "displayValue": "3,908",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Domination Revenges",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 591,
    "displayValue": "591",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Bombs Planted",
    "displayCategory": "Objective",
    "category": "objective",
    "metadata": {},
    "value": 10598,
    "displayValue": "10,598",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Bombs Defused",
    "displayCategory": "Objective",
    "category": "objective",
    "metadata": {},
    "value": 649,
    "displayValue": "649",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Money Earned",
    "displayCategory": "Objective",
    "category": "objective",
    "metadata": {},
    "value": 452413700,
    "displayValue": "452,413,700",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Hostages Rescued",
    "displayCategory": "Objective",
    "category": "objective",
    "metadata": {},
    "value": 572,
    "displayValue": "572",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "MVP",
    "displayCategory": "Objective",
    "category": "objective",
    "metadata": {},
    "value": 20452,
    "displayValue": "20,452",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Wins",
    "displayCategory": "Round",
    "category": "round",
    "metadata": {},
    "value": 10101,
    "displayValue": "10,101",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Ties",
    "displayCategory": "Round",
    "category": "round",
    "metadata": {},
    "value": 0,
    "displayValue": "0",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Matches Played",
    "displayCategory": "Round",
    "category": "round",
    "metadata": {},
    "value": 17182,
    "displayValue": "17,182",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Losses",
    "displayCategory": "Round",
    "category": "round",
    "metadata": {},
    "value": 7081,
    "displayValue": "7,081",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Rounds Played",
    "displayCategory": "Round",
    "category": "round",
    "metadata": {},
    "value": 138089,
    "displayValue": "138,089",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Rounds Won",
    "displayCategory": "Round",
    "category": "round",
    "metadata": {},
    "value": 10101,
    "displayValue": "10,101",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Win %",
    "displayCategory": "Round",
    "category": "round",
    "metadata": {},
    "value": 58.8,
    "displayValue": "58.8%",
    "displayType": "NumberPercentage"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Headshot %",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 80.7,
    "displayValue": "80.7%",
    "displayType": "NumberPercentage"
  }
];

const Splitgate = [{
    "rank": null,
    "percentile": 99.9,
    "displayName": "Points",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 41788,
    "displayValue": "41,788",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Kills",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 20720,
    "displayValue": "20,720",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Assists",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 5381,
    "displayValue": "5,381",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Deaths",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 9144,
    "displayValue": "9,144",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Suicides",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 101,
    "displayValue": "101",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.7,
    "displayName": "Teabags",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 258,
    "displayValue": "258",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Melee Kills",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 2322,
    "displayValue": "2,322",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Portal Kills",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 16,
    "displayValue": "16",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Kills Thru Portal",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 738,
    "displayValue": "738",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Damage Dealt",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 2317870,
    "displayValue": "2,317,870",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Matches Played",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 1040,
    "displayValue": "1,040",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Wins",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 782,
    "displayValue": "782",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Losses",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 258,
    "displayValue": "258",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 80.0,
    "displayName": "Win %",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 75.19,
    "displayValue": "75.2%",
    "displayType": "NumberPercentage"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Time Played",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 438992,
    "displayValue": "5d 01h 56m",
    "displayType": "TimeSeconds"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Headshots Landed",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 11124,
    "displayValue": "11,124",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Collaterals",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 373,
    "displayValue": "373",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Headshot Kills",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 4941,
    "displayValue": "4,941",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 58.0,
    "displayName": "Headshot Accuracy %",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 13.93,
    "displayValue": "13.9%",
    "displayType": "NumberPercentage"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Shots Fired",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 203958,
    "displayValue": "203,958",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Shots Landed",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 79863,
    "displayValue": "79,863",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 98.9,
    "displayName": "Shots Accuracy %",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 39.16,
    "displayValue": "39.2%",
    "displayType": "NumberPercentage"
  },
  {
    "rank": null,
    "percentile": 91.0,
    "displayName": "K/D",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 2.27,
    "displayValue": "2.27",
    "displayType": "NumberPrecision2"
  },
  {
    "rank": null,
    "percentile": 89.0,
    "displayName": "KA/D",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 2.85,
    "displayValue": "2.85",
    "displayType": "NumberPrecision2"
  },
  {
    "rank": null,
    "percentile": 78.0,
    "displayName": "Kills/min",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 2.0,
    "displayValue": "2.00",
    "displayType": "NumberPrecision2"
  },
  {
    "rank": null,
    "percentile": 94.0,
    "displayName": "Kills/match",
    "displayCategory": "Combat",
    "category": "combat",
    "metadata": {},
    "value": 19.0,
    "displayValue": "19.00",
    "displayType": "NumberPrecision2"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Double Kills",
    "displayCategory": "Medals",
    "category": "medals",
    "metadata": {},
    "value": 2604,
    "displayValue": "2,604",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Triple Kills",
    "displayCategory": "Medals",
    "category": "medals",
    "metadata": {},
    "value": 470,
    "displayValue": "470",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Killeidoscope!",
    "displayCategory": "Medals",
    "category": "medals",
    "metadata": {},
    "value": 95,
    "displayValue": "95",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Killiteration!",
    "displayCategory": "Medals",
    "category": "medals",
    "metadata": {},
    "value": 15,
    "displayValue": "15",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Sextuple Kills",
    "displayCategory": "Medals",
    "category": "medals",
    "metadata": {},
    "value": 5,
    "displayValue": "5",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Killstreak: 5 Kills",
    "displayCategory": "Medals",
    "category": "medals",
    "metadata": {},
    "value": 1295,
    "displayValue": "1,295",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Killstreak: 10 Kills",
    "displayCategory": "Medals",
    "category": "medals",
    "metadata": {},
    "value": 320,
    "displayValue": "320",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Killstreak: 15 Kills",
    "displayCategory": "Medals",
    "category": "medals",
    "metadata": {},
    "value": 95,
    "displayValue": "95",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Killstreak: 20 Kills",
    "displayCategory": "Medals",
    "category": "medals",
    "metadata": {},
    "value": 30,
    "displayValue": "30",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Killstreak: 25 Kills",
    "displayCategory": "Medals",
    "category": "medals",
    "metadata": {},
    "value": 11,
    "displayValue": "11",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Killstreak: 50 Kills",
    "displayCategory": "Medals",
    "category": "medals",
    "metadata": {},
    "value": 0,
    "displayValue": "0",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Rank",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": null,
    "displayValue": null,
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Rank XP",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": null,
    "displayValue": null,
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Level",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 100,
    "displayValue": "100",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": 99.9,
    "displayName": "Level XP",
    "displayCategory": "General",
    "category": "general",
    "metadata": {},
    "value": 5140124,
    "displayValue": "5,140,124",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Platinum",
    "displayCategory": "General",
    "category": "general",
    "metadata": {
      "label": "Top Playlist Rank",
      "iconUrl": "https://trackercdn.com/cdn/tracker.gg/splitgate/ranks/platinum.png"
    },
    "value": 2890,
    "displayValue": "2,890",
    "displayType": "Number"
  },
  {
    "rank": null,
    "percentile": null,
    "displayName": "Progression",
    "displayCategory": null,
    "category": null,
    "metadata": {},
    "value": 78.15631262525051,
    "displayValue": "78.2%",
    "displayType": "NumberPercentage"
  }
];